// All 252 incorporated municipalities in Vermont (cities, towns, gores) plus
// commonly-recognized village names like "Essex Junction" and "Morrisville"
// (the village within Morristown). Sorted alphabetically with locale-aware
// comparison so apostrophes and punctuation are handled the way readers expect.

const VERMONT_TOWN_NAMES: readonly string[] = [
  "Burlington",
  "Essex",
  "South Burlington",
  "Colchester",
  "Rutland",
  "Bennington",
  "Brattleboro",
  "Milton",
  "Hartford",
  "Williston",
  "Essex Junction",
  "Springfield",
  "Middlebury",
  "Barre",
  "Montpelier",
  "St. Johnsbury",
  "Winooski",
  "Shelburne",
  "St. Albans",
  "Swanton",
  "Northfield",
  "Waterbury",
  "Manchester",
  "Lyndon",
  "Stowe",
  "Jericho",
  "Hinesburg",
  "Newport",
  "Charlotte",
  "Castleton",
  "Bristol",
  "Brandon",
  "Richmond",
  "Cambridge",
  "Hartland",
  "Underhill",
  "Norwich",
  "Hyde Park",
  "Pittsford",
  "Westford",
  "Hardwick",
  "Fairfax",
  "Fair Haven",
  "Putney",
  "Rockingham",
  "Morristown",
  "Bradford",
  "Vergennes",
  "Fairfield",
  "West Rutland",
  "Georgia",
  "Pownal",
  "Bethel",
  "Ferrisburgh",
  "Chester",
  "Westminster",
  "Wilmington",
  "Shaftsbury",
  "Dorset",
  "Wallingford",
  "Addison",
  "Albany",
  "Alburgh",
  "Andover",
  "Arlington",
  "Athens",
  "Averill",
  "Avery's Gore",
  "Bakersfield",
  "Baltimore",
  "Barnard",
  "Barnet",
  "Belvidere",
  "Benson",
  "Berkshire",
  "Berlin",
  "Bloomfield",
  "Bolton",
  "Braintree",
  "Brighton",
  "Brookfield",
  "Brookline",
  "Brownington",
  "Brunswick",
  "Buel's Gore",
  "Burke",
  "Cabot",
  "Calais",
  "Canaan",
  "Cavendish",
  "Charleston",
  "Chelsea",
  "Chittenden",
  "Clarendon",
  "Concord",
  "Corinth",
  "Cornwall",
  "Coventry",
  "Craftsbury",
  "Danby",
  "Danville",
  "Derby",
  "Dover",
  "Dummerston",
  "Duxbury",
  "East Haven",
  "East Montpelier",
  "Eden",
  "Elmore",
  "Enosburgh",
  "Fairlee",
  "Fayston",
  "Ferdinand",
  "Fletcher",
  "Franklin",
  "Glastenbury",
  "Glover",
  "Goshen",
  "Grafton",
  "Granby",
  "Grand Isle",
  "Granville",
  "Greensboro",
  "Groton",
  "Guildhall",
  "Guilford",
  "Halifax",
  "Hancock",
  "Highgate",
  "Holland",
  "Hubbardton",
  "Huntington",
  "Ira",
  "Irasburg",
  "Isle La Motte",
  "Jamaica",
  "Jay",
  "Johnson",
  "Killington",
  "Kirby",
  "Landgrove",
  "Leicester",
  "Lemington",
  "Lewis",
  "Lincoln",
  "Londonderry",
  "Lowell",
  "Ludlow",
  "Lunenburg",
  "Maidstone",
  "Marlboro",
  "Marshfield",
  "Mendon",
  "Middlesex",
  "Middletown Springs",
  "Monkton",
  "Montgomery",
  "Moretown",
  "Morgan",
  "Morrisville",
  "Mount Holly",
  "Mount Tabor",
  "New Haven",
  "Newark",
  "Newbury",
  "Newfane",
  "North Hero",
  "Orange",
  "Orwell",
  "Panton",
  "Pawlet",
  "Peacham",
  "Peru",
  "Pittsfield",
  "Plainfield",
  "Plymouth",
  "Pomfret",
  "Poultney",
  "Proctor",
  "Randolph",
  "Reading",
  "Readsboro",
  "Richford",
  "Ripton",
  "Rochester",
  "Roxbury",
  "Royalton",
  "Rupert",
  "Ryegate",
  "Salisbury",
  "Sandgate",
  "Searsburg",
  "Sharon",
  "Sheffield",
  "Sheldon",
  "Shoreham",
  "Shrewsbury",
  "Somerset",
  "South Hero",
  "Stamford",
  "Stannard",
  "Starksboro",
  "Stockbridge",
  "Strafford",
  "Stratton",
  "Sudbury",
  "Sunderland",
  "Sutton",
  "Thetford",
  "Tinmouth",
  "Topsham",
  "Townshend",
  "Troy",
  "Tunbridge",
  "Vernon",
  "Vershire",
  "Victory",
  "Waitsfield",
  "Walden",
  "Waltham",
  "Wardsboro",
  "Warner's Grant",
  "Warren",
  "Warren's Gore",
  "Washington",
  "Waterford",
  "Waterville",
  "Weathersfield",
  "Wells",
  "West Fairlee",
  "West Haven",
  "West Windsor",
  "Westfield",
  "Weston",
  "Weybridge",
  "Wheelock",
  "Whiting",
  "Whitingham",
  "Williamstown",
  "Windham",
  "Windsor",
  "Winhall",
  "Wolcott",
  "Woodbury",
  "Woodford",
  "Woodstock",
  "Worcester",
];

export const VERMONT_TOWNS: readonly string[] = [...VERMONT_TOWN_NAMES].sort(
  (a, b) => a.localeCompare(b)
);
